# Generated by Django 6.0.2 on 2026-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='anomaly_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='cancellation_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='classification_label',
            field=models.CharField(choices=[('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk')], default='low_risk', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='model_version',
            field=models.CharField(default='hybrid_v2', max_length=40),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='stale_pending_ratio',
            field=models.FloatField(default=0),
        ),
    ]
