# Generated by Django 6.0.2 on 2026-02-14 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sellerrisksnapshot_anomaly_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRiskIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('frozen_fine_pending', 'Frozen - Fine Pending'), ('fine_paid', 'Fine Paid'), ('appealed', 'Appealed'), ('under_review', 'Under Review'), ('resolved_unfrozen', 'Resolved - Unfrozen'), ('resolved_frozen', 'Resolved - Frozen')], default='frozen_fine_pending', max_length=32)),
                ('risk_score', models.FloatField(default=0.0)),
                ('classification_label', models.CharField(choices=[('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk')], default='high_risk', max_length=20)),
                ('incident_reason', models.TextField(blank=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine_paid_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_text', models.TextField(blank=True)),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('seller_notified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_decision_note', models.TextField(blank=True)),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_incidents', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='analytics.sellerrisksnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
