# Generated by Django 6.0.2 on 2026-02-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_sellerriskincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerriskincident',
            name='seller_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='feature_vector',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='risk_velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerriskincident',
            name='status',
            field=models.CharField(choices=[('frozen_fine_pending', 'Frozen - Fine Pending'), ('fine_paid', 'Fine Paid'), ('appealed', 'Appealed'), ('under_review', 'Under Review'), ('resolved_unfrozen', 'Resolved - Unfrozen'), ('resolved_frozen', 'Resolved - Frozen'), ('resolved_terminated', 'Resolved - Terminated')], default='frozen_fine_pending', max_length=32),
        ),
    ]
