# Generated by Django 6.0.2 on 2026-02-15 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_sellerriskincident_seller_acknowledged_at_and_more'),
        ('orders', '0004_booking_anomaly_incident_booking_anomaly_reported_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='seller_fraud', max_length=60)),
                ('version', models.CharField(max_length=60, unique=True)),
                ('algorithm', models.CharField(default='hybrid_logistic', max_length=80)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('staging', 'Staging'), ('production', 'Production'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('bias', models.FloatField(default=0.0)),
                ('decision_threshold', models.FloatField(default=0.7)),
                ('feature_weights', models.JSONField(blank=True, default=dict)),
                ('calibration_bins', models.JSONField(blank=True, default=list)),
                ('drift_baseline', models.JSONField(blank=True, default=dict)),
                ('quality_metrics', models.JSONField(blank=True, default=dict)),
                ('training_window_start', models.DateTimeField(blank=True, null=True)),
                ('training_window_end', models.DateTimeField(blank=True, null=True)),
                ('training_samples', models.PositiveIntegerField(default=0)),
                ('positive_samples', models.PositiveIntegerField(default=0)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='calibrated_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='decision_threshold',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='drift_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='model_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='network_risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='sequence_risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerrisksnapshot',
            name='top_contributors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RiskModelBacktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('precision_score', models.FloatField(default=0)),
                ('recall_score', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('auc_score', models.FloatField(default=0)),
                ('confusion_matrix', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='analytics.riskmodelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskDriftSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_drift_score', models.FloatField(default=0)),
                ('feature_drift', models.JSONField(blank=True, default=dict)),
                ('is_alert', models.BooleanField(default=False)),
                ('snapshot_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_snapshots', to='analytics.riskmodelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskPerformanceDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_f1_score', models.FloatField(default=0)),
                ('current_f1_score', models.FloatField(default=0)),
                ('drift_score', models.FloatField(default=0)),
                ('is_alert', models.BooleanField(default=False)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_drifts', to='analytics.riskmodelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskRealtimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_cancelled', 'Booking Cancelled'), ('payment_failed', 'Payment Failed'), ('payment_success', 'Payment Success'), ('manual_review', 'Manual Review')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.FloatField(default=0)),
                ('calibrated_probability', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='orders.booking')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_realtime_events', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_events', to='analytics.sellerrisksnapshot')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='orders.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
