# Generated by Django 6.0.2 on 2026-02-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_customeraddress'),
        ('locations', '0002_state_alter_district_options_alter_district_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_customer_addresses', to='locations.location'),
        ),
    ]
