# Generated by Django 6.0.2 on 2026-02-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customeraddress_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='suspension_note',
            field=models.TextField(blank=True),
        ),
    ]
