# Generated by Django 6.0.2 on 2026-02-14 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0002_state_alter_district_options_alter_district_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='product_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='product',
            name='serviceable_districts',
            field=models.ManyToManyField(blank=True, related_name='products_serviceable_by_district', to='locations.district'),
        ),
        migrations.AddField(
            model_name='product',
            name='serviceable_locations',
            field=models.ManyToManyField(blank=True, related_name='products_serviceable_by_location', to='locations.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='serviceable_states',
            field=models.ManyToManyField(blank=True, related_name='products_serviceable_by_state', to='locations.state'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
