# Generated by Django 6.0.2 on 2026-02-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_photo_product_serviceable_districts_and_more'),
        ('locations', '0002_state_alter_district_options_alter_district_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='non_serviceable_locations',
            field=models.ManyToManyField(blank=True, related_name='products_non_serviceable_by_location', to='locations.location'),
        ),
    ]
