# Generated by Django 6.0.2 on 2026-02-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_sellerriskincident'),
        ('orders', '0003_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='anomaly_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalous_cancellation_bookings', to='analytics.sellerriskincident'),
        ),
        migrations.AddField(
            model_name='booking',
            name='anomaly_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_impact',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('no_impact', 'No Impact'), ('negative_impact', 'Negative Impact')], default='not_reviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_impact_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_booking_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by_role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
